const diablo2RunesObject = {
    "1": { name: "El", number: 1, reqLevel: 11, neededForCube: { higherRune: "Eld", count: 3 }, cubable: false, dropped: 0, gems: "", usedInProject: false },
    "2": { name: "Eld", number: 2, reqLevel: 11, neededForCube: { higherRune: "Tir", count: 3 }, cubable: false, dropped: 0, gems: "", usedInProject: false },
    "3": { name: "Tir", number: 3, reqLevel: 13, neededForCube: { higherRune: "Nef", count: 3 }, cubable: false, dropped: 0, gems: "", usedInProject: false },
    "4": { name: "Nef", number: 4, reqLevel: 13, neededForCube: { higherRune: "Eth", count: 3 }, cubable: false, dropped: 0, gems: "", usedInProject: false },
    "5": { name: "Eth", number: 5, reqLevel: 15, neededForCube: { higherRune: "Ith", count: 3 }, cubable: false, dropped: 0, gems: "", usedInProject: false },
    "6": { name: "Ith", number: 6, reqLevel: 15, neededForCube: { higherRune: "Tal", count: 3 }, cubable: false, dropped: 0, gems: "", usedInProject: false },
    "7": { name: "Tal", number: 7, reqLevel: 17, neededForCube: { higherRune: "Ral", count: 3 }, cubable: false, dropped: 0, gems: "", usedInProject: false },
    "8": { name: "Ral", number: 8, reqLevel: 19, neededForCube: { higherRune: "Ort", count: 3 }, cubable: false, dropped: 0, gems: "", usedInProject: false },
    "9": { name: "Ort", number: 9, reqLevel: 21, neededForCube: { higherRune: "Thul", count: 3 }, cubable: true, dropped: 0, gems: "Chipped Topaz", usedInProject: false },
    "10": { name: "Thul", number: 10, reqLevel: 23, neededForCube: { higherRune: "Amn", count: 3 }, cubable: true, dropped: 0, gems: "Chipped Amethyst", usedInProject: false },
    "11": { name: "Amn", number: 11, reqLevel: 25, neededForCube: { higherRune: "Sol", count: 3 }, cubable: true, dropped: 0, gems: "Chipped Amethyst", usedInProject: false },
    "12": { name: "Sol", number: 12, reqLevel: 27, neededForCube: { higherRune: "Shael", count: 3 }, cubable: true, dropped: 0, gems: "Chipped Sapphire", usedInProject: false },
    "13": { name: "Shael", number: 13, reqLevel: 29, neededForCube: { higherRune: "Dol", count: 3 }, cubable: true, dropped: 0, gems: "Chipped Ruby", usedInProject: false },
    "14": { name: "Dol", number: 14, reqLevel: 31, neededForCube: { higherRune: "Hel", count: 3 }, cubable: true, dropped: 0, gems: "Chipped Emerald", usedInProject: false },
    "15": { name: "Hel", number: 15, reqLevel: 0, neededForCube: { higherRune: "Io", count: 3 }, cubable: true, dropped: 0, gems: "Chipped Diamond", usedInProject: false },
    "16": { name: "Io", number: 16, reqLevel: 35, neededForCube: { higherRune: "Lum", count: 3 }, cubable: true, dropped: 0, gems: "Flawed Topaz", usedInProject: false },
    "17": { name: "Lum", number: 17, reqLevel: 37, neededForCube: { higherRune: "Ko", count: 3 }, cubable: true, dropped: 0, gems: "Flawed Amethyst", usedInProject: false },
    "18": { name: "Ko", number: 18, reqLevel: 39, neededForCube: { higherRune: "Fal", count: 3 }, cubable: true, dropped: 0, gems: "Flawed Sapphire", usedInProject: false },
    "19": { name: "Fal", number: 19, reqLevel: 41, neededForCube: { higherRune: "Lem", count: 3 }, cubable: true, dropped: 0, gems: "Flawed Ruby", usedInProject: false },
    "20": { name: "Lem", number: 20, reqLevel: 43, neededForCube: { higherRune: "Pul", count: 3 }, cubable: true, dropped: 0, gems: "Flawed Emerald", usedInProject: false },
    "21": { name: "Pul", number: 21, reqLevel: 45, neededForCube: { higherRune: "Um", count: 2 }, cubable: true, dropped: 0, gems: "Flawed Diamond", usedInProject: false },
    "22": { name: "Um", number: 22, reqLevel: 47, neededForCube: { higherRune: "Mal", count: 2 }, cubable: true, dropped: 0, gems: "Topaz", usedInProject: false },
    "23": { name: "Mal", number: 23, reqLevel: 49, neededForCube: { higherRune: "Ist", count: 2 }, cubable: true, dropped: 0, gems: "Amethyst", usedInProject: false },
    "24": { name: "Ist", number: 24, reqLevel: 51, neededForCube: { higherRune: "Gul", count: 2 }, cubable: true, dropped: 0, gems: "Sapphire", usedInProject: false },
    "25": { name: "Gul", number: 25, reqLevel: 53, neededForCube: { higherRune: "Vex", count: 2 }, cubable: true, dropped: 0, gems: "Ruby", usedInProject: false },
    "26": { name: "Vex", number: 26, reqLevel: 55, neededForCube: { higherRune: "Ohm", count: 2 }, cubable: true, dropped: 0, gems: "Emerald", usedInProject: false },
    "27": { name: "Ohm", number: 27, reqLevel: 57, neededForCube: { higherRune: "Lo", count: 2 }, cubable: true, dropped: 0, gems: "Diamond", usedInProject: false },
    "28": { name: "Lo", number: 28, reqLevel: 59, neededForCube: { higherRune: "Sur", count: 2 }, cubable: true, dropped: 0, gems: "Flawless Topaz", usedInProject: false },
    "29": { name: "Sur", number: 29, reqLevel: 61, neededForCube: { higherRune: "Ber", count: 2 }, cubable: true, dropped: 0, gems: "Flawless Amethyst", usedInProject: false },
    "30": { name: "Ber", number: 30, reqLevel: 63, neededForCube: { higherRune: "Jah", count: 2 }, cubable: true, dropped: 0, gems: "Flawless Sapphire", usedInProject: false },
    "31": { name: "Jah", number: 31, reqLevel: 65, neededForCube: { higherRune: "Cham", count: 2 }, cubable: true, dropped: 0, gems: "Flawless Ruby", usedInProject: false },
    "32": { name: "Cham", number: 32, reqLevel: 67, neededForCube: { higherRune: "Zod", count: 1 }, cubable: true, dropped: 0, gems: "Flawless Emerald", usedInProject: false },
    "33": { name: "Zod", number: 33, reqLevel: 69, neededForCube: { higherRune: "", count: 0 }, cubable: false, dropped: 0, gems: "", usedInProject: false }
  };
  
  console.log(diablo2RunesObject);
  